phonebook/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from phones import views as phones_views
from users import views as users_views

router = DefaultRouter()
router.register('phones/show', phones_views.PhoneBookViewSets)
router.register('users', users_views.UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('phones.urls')),
    path('users/', include('users.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/', include(router.urls)),
]

phones/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from . import views
from .views import ShowPhoneNumbers, AddPhoneNumber, UpdatePhoneBook, DeletePhoneBook

router = DefaultRouter()
router.register('phones', views.PhoneBookViewSets)

app_name = 'phones'
urlpatterns = [
    path('', ShowPhoneNumbers.as_view(), name='show'),
    path('create/', AddPhoneNumber.as_view(), name='create'),
    path('edit/<int:pk>', UpdatePhoneBook.as_view(), name='edit'),
    path('<pk>/delete/', DeletePhoneBook.as_view(), name='delete'),
    path('find/', views.find_entry, name='find'),
    path('search/', views.show_search_form, name='search'),
    path('api/v1/', include(router.urls)),
]

users/urls.py
from django.urls import path
# from rest_framework.routers import DefaultRouter

from .views import Login, Logout

app_name = 'users'
urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

phones/models.py
from django.core.validators import RegexValidator
from django.utils.translation import ugettext_lazy as _
from django.db import models

phone_regex = RegexValidator(regex='^0[0-9]{2,}[0-9]{7,}$', message='phone number invalid')


class Entry(models.Model):
    """
    An entry in the phonebook
    """
    username = models.ForeignKey('auth.User', verbose_name=_('صاحب دفترچه'), on_delete=models.PROTECT, null=True,
                                 blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('زمان ساخت'))
    first_name = models.CharField(max_length=100, verbose_name=_('نام'))
    last_name = models.CharField(max_length=100, verbose_name=_('نام خانوادگی'))
    phone_number = models.CharField(validators=[phone_regex], max_length=11, unique=True, verbose_name=_('شماره تلفن'))

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = _('دفترچه تلفن')
        verbose_name_plural = _('دفترچه تلفن ها')

phones/forms.py
from django import forms
from . import models


class EntryForm(forms.ModelForm):
    class Meta:
        model = models.Entry
        fields = (
            'username',
            'first_name',
            'last_name',
            'phone_number',
        )

phones/views.py
from rest_framework import generics, viewsets, permissions, mixins
from rest_framework.permissions import IsAuthenticated

# from .serializers import EntrySerializers
import logging

import weasyprint
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.decorators.http import require_GET
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from . import models
from .forms import EntryForm
from .models import Entry
from .serializers import EntrySerializers

logger = logging.getLogger(__name__)


class ShowPhoneNumbers(ListView):
    model = Entry
    template_name = 'phones/show_phone_book.html'
    logger.info("your list contacts is totally true")

    def get_queryset(self):
        if self.request.user.is_authenticated:
            logger.info(f'{self.request.user} is authenticated')
            return Entry.objects.filter(username=self.request.user)
        if not self.request.user.is_authenticated:
            logger.warning("Didn't login")


class AddPhoneNumber(CreateView):
    model = Entry
    template_name = 'phones/add_entry.html'
    success_url = reverse_lazy('phones:show')

    fields = [
        'username',
        'first_name',
        'last_name',
        'phone_number',
    ]

    def get_queryset(self):
        qs = self.request.user
        logger.info(
            f'a contact in the name {self.request.first_name} {self.request.last_name} is added to phone book by {self.request.user};')
        return require_GET.usename.filter(username=qs)


class UpdatePhoneBook(UpdateView):
    form_class = EntryForm
    template_name = "phones/edit_entry.html"
    success_url = reverse_lazy('phones:show')

    def get_queryset(self):
        queryset = Entry.objects.all()
        logger.warning(
            f'a contact is edited by {self.request.user};')
        return queryset


class DeletePhoneBook(DeleteView):
    model = Entry
    template_name = 'phones/entry_confirm_delete.html'
    success_url = reverse_lazy('phones:show')


def find_entry(request):
    """
    Finds a phonebook entry
    """
    phone_number = request.GET.get('num', None)
    type_search = request.GET.get('type_search')
    print("type_search", type_search)
    qs = None

    if not phone_number:
        return JsonResponse({'success': False, 'error': 'No number specified.'}, status=400)

    if type_search == 'contains':
        qs = Entry.objects.filter(phone_number__contains=phone_number, username=request.user)
        print(type_search)
    if type_search == 'startswith':
        qs = Entry.objects.filter(phone_number__startswith=phone_number, username=request.user)
        print(type_search)
    if type_search == 'endswith':
        qs = Entry.objects.filter(phone_number__endswith=phone_number, username=request.user)
        print(type_search)
    if type_search == 'exact':
        qs = Entry.objects.filter(phone_number__exact=phone_number, username=request.user)
        print(type_search)

    request.session['action'] = [f'search type: {type_search}\nnumber search: {phone_number}']
    print(qs)

    return JsonResponse(
        {
            'results': list(
                qs.values()
            ),
            'count': qs.count()
        }
        , status=200
    )


@require_GET
def show_search_form(request):
    """
    Show the search form page
    """
    return render(request, 'phones/search.html')


"""
DRF Views
"""


class PhoneBookViewSets(mixins.CreateModelMixin, mixins.ListModelMixin, mixins.UpdateModelMixin,
                        viewsets.GenericViewSet):
    queryset = Entry.objects.all()
    serializer_class = EntrySerializers
    permission_classes = [permissions.IsAuthenticated]
    lookup_field = 'pk'

    filter_fields = (
        'phone_number',
        'first_name',
        'last_name',
    )

    def get_queryset(self):
        qs = Entry.objects.filter(username=self.request.user)
        return qs


class PrintPhoneNumber(DetailView):
    model = models.Entry

    def get(self, request, *args, **kwargs):
        # Call parents as normal
        g = super(PrintPhoneNumber, self).get(request, *args, **kwargs)

        # Get the rendered content and pass it to w-easy-print
        rendered_content = g.rendered_content
        pdf = weasyprint.HTML(string=rendered_content).write_pdf()

        # Create a new http response with pdf mime type
        response = HttpResponse(pdf, content_type='application/pdf')
        logger.info("Your print PDF mode is working")
        return response

# class PhoneNumberShow(generics.ListAPIView):
#     queryset = models.Entry.objects.all()
#     serializer_class = EntrySerializers
#     permission_classes = [IsAuthenticated]
#
#     def get_queryset(self):
#         qs = super().get_queryset()
#         qs = qs.filter(username=self.request.user)
#         return qs
#
#
# class PhoneNumberCreate(generics.CreateAPIView):
#     queryset = models.Entry.objects.all()
#     serializer_class = EntrySerializers
#     permission_classes = [IsAuthenticated]
#
#
# class PhoneNumberUpdate(generics.UpdateAPIView):
#     queryset = models.Entry.objects.all()
#     serializer_class = EntrySerializers


# class PhoneNumberUpdate(generics.ListCreateAPIView):
#     queryset = models.Entry.objects.all()
#     serializer_class = EntrySerializers
#     permission_classes = [IsAuthenticated]
#
#     def partial_update(self, request):
#         queryset = self.get_queryset()
#         serializer = EntrySerializers(queryset, many=True)
#         return Response(serializer.data)

phones/templates/phones/add_entry.html
{% extends 'phones/base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load static %}

{% block page_header_title %}
    {% trans 'اضافه کردن به دفترچه تلفن' %}
{% endblock %}


{% block content %}
    <div class="container">
        <h2>{% trans 'دفترچه تلفن جدید' %}</h2>
        <form method="post">
            {% csrf_token %}
            {#            {{ form.username }}#}
{#            {% for people in form.username %}#}
{#                {% if people is not requst.user %}#}
{#                    {{ form.username.remove(people) }}#}
{#                {% endif %}#}
{#            {% endfor %}#}
            {% trans 'صاحب دفترچه تلفن:' %}
            {{ form.username }}
            <br><br>
            {% trans 'نام:' %}
            {{ form.first_name }}
            <br><br>
            {% trans 'نام خانوادگی:' %}
            {{ form.last_name }}
            <br><br>
            {% trans 'شماره تلفن:' %}
            {{ form.phone_number }}
            <br><br>
            <button type="submit" class="btn btn-outline-success" id="send-form">{% trans 'اضافه کردن' %}</button>
        </form>
    </div>
{% endblock %}

phones/templates/phones/base.html
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% trans 'دفترچه تلفن' %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'js/jquery-3.6.0.min.js' %}" rel="stylesheet">
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'phones:show' %}"><b>{% trans 'صفحه اصلی' %}</b></a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'phones:create' %}">{% trans 'اضافه کردن' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'phones:search' %}">{% trans 'جستوجو' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">{% trans 'خروج' %}</a>
                    </li>
                {% endif %}
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">{% trans 'ورود' %}</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        {{ request.user }}
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<div class="row mb-4 mt-4">
    {% block content %}YOUR CONTENT GOES HERE{% endblock %}
</div>

{#<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"#}
{#        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"#}
{#        crossorigin="anonymous"></script>#}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous"></script>

{% block page_scripts %}{% endblock %}

</body>
</html>

phones/templates/phones/edit_entry.html
{% extends 'phones/base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load static %}

{% block page_header_title %}
    {% trans 'تغییر در دفترچه تلفن' %}
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-outline-success" id="send-form">{% trans 'اعمال تغییرات' %}</button>
        </form>
    </div>
{% endblock %}

phones/templates/phones/entry_confirm_delete.html
{% extends 'phones/base.html' %}
{% load widget_tweaks %}
{% load i18n %}
{% load static %}

{% block page_header_title %}
    {% trans 'حذف دفترچه تلفن' %}
{% endblock %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}" contact?</p>
            <input value="{% trans 'تایید' %}" type="submit" class="btn btn-success">
            <a href="{% url 'phones:show' %}" class="btn btn-danger">{% trans 'انصراف' %}</a>
        </form>
    </div>
{% endblock %}

phones/templates/phones/entry_detail.html
{% load i18n %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">{% trans 'نام' %}</th>
      <th scope="col">{% trans 'نام خانوادگی' %}</th>
      <th scope="col">{% trans 'شماره تلفن' %}</th>
    </tr>
  </thead>
  <tbody>
  {% for object in object_list %}
    <tr>
        <td>{{ object.first_name }}</td>
        <td>{{ object.last_name }}</td>
        <td>{{ object.phone_number }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

phones/templates/phones/search.html
{% extends 'phones/base.html' %}
{% load i18n %}
{% load static %}

{% block page_header_title %}
    {% trans 'جستوجو در دفترچه تلفن' %}
{% endblock %}

{% block content %}
    <div class="container">
        <h2>{% trans 'جستوجو در دفترچه تلفن' %}</h2>
        <div class="row">
            <div class="col-5">
                <form>
                    <label for="query">{% trans 'لطفا عدد مورد نظر خود را وارد نمایید' %}</label>
                    <input type="text" id="query">
                    <select id="type_search" class="form-select" aria-label="Default select example">
                        <option value="contains">{% trans 'شامل شماره تلفن باشد' %}</option>
                        <option value="startswith">{% trans 'با این عدد شروع شود' %}</option>
                        <option value="endswith">{% trans 'با این عدد تمام شود' %}</option>
                        <option value="exact">{% trans 'دقیقا همین عدد باشد' %}</option>
                    </select>
                </form>
                <button type="submit" class="btn btn-outline-dark" id="search-btn">🔎</button>
            </div>
            <div class="col-7">
                <table class="table table-dark">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% trans 'نام' %}</th>
                        <th scope="col">{% trans 'نام خانوادگی' %}</th>
                        <th scope="col">{% trans 'شماره تلفن' %}</th>
                    </tr>
                    </thead>
                    <tbody id="output-div">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_scripts %}
    <script>
        $(document).ready(function () {
            $('#search-btn').click(function () {
                console.log("hello");
                var query_text = $('#query').val();
                var type_search = $('#type_search option:selected').val();
                var ajax_config = {
                    url: '/find/',
                    data: {
                        num: query_text,
                        type_search: type_search
                    },
                    method: 'get',
                    success: function (response) {
                        var my_output_div = $('#output-div');
                        my_output_div.empty();
                        $(response.results).each(function (index, obj) {
                            var my_table = '<tr><th scope="row">' + (index + 1) + '</th>' +
                                '<td>' + obj.first_name + '</td><td>' + obj.last_name + '</td>' +
                                '<td>' + obj.phone_number + '</td></tr>';
                            my_output_div.append(my_table);
                        });
                    },
                };
                $.ajax(ajax_config);
            });
        });
    </script>
{% endblock %}

phones/templates/phones/show_phone_book.html
{% extends 'phones/base.html' %}
{% load i18n %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% block content %}
    <div class="container">
        {% if user.is_authenticated %}
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">{% trans 'نام' %}</th>
                    <th scope="col">{% trans 'نام خانوادگی' %}</th>
                    <th scope="col">{% trans 'شماره تلفن' %}</th>
                    <th scope="col">{% trans 'صاحب دفترچه تلفن' %}</th>
                    <th scope="col">{% trans 'عملیات ها' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for phones in object_list %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ phones.first_name }}</td>
                        <td>{{ phones.last_name }}</td>
                        <td>{{ phones.phone_number }}</td>
                        <td>{{ phones.username }}</td>
                        <td>
                            <a href="{% url 'phones:edit' phones.pk %}" class="btn btn-primary">
                                <i class="fa f044">{% trans 'ایجاد تغییرات' %}</i>
                            </a>
                            <a href="{% url 'phones:delete' phones.pk %}" class="btn btn-primary">
                                <i class="fa f044">{% trans 'حذف' %}</i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
        {% if not user.is_authenticated %}
            {% trans 'لطفا ابتدا وارد شوید' %}
        {% endif %}
    </div>
{% endblock %}